apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: gw-a
spec:
  profile: minimal # istiod is required for gateway injection to function
  components:
    ingressGateways:
    - name: gateway-a
      namespace: ns-a
      enabled: true
      label:
        istio: gw-a
    - name: gateway-b
      namespace: ns-b
      enabled: true
      label:
        istio: gw-b
